import Header from "@/layouts/Header";
import Head from "next/head";
import Footer from "../Footer";

const Layout = (props) => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center bg-textlight">
        <Header />
        {props.children}
        <Footer />
      </main>
    </>
  );
};

export default Layout;
